name: Deploy Homer to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repozytorium
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Instalacja zależności
        run: pnpm install

      - name: Budowanie projektu
        run: pnpm build

      - name: Deploy na GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.G_TOKEN }}
          path: ./dist
