name: Sync Fork with Upstream

on:
  schedule:
    - cron: '55 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: master

    - name: Configure Git for GitHub Actions
      run: |
        git config user.name "GitHub Actions"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf "https://github.com"

    - name: Fetch upstream changes
      run: |
        git remote add upstream https://github.com/bastienwirtz/homer.git
        git fetch upstream

    - name: Merge upstream changes
      run: |
        git checkout master
        git merge upstream/main --allow-unrelated-histories -m "Sync fork with upstream" || echo "No changes to merge"

    - name: Check if changes exist
      id: changes
      run: |
        git diff --exit-code || echo "Changes detected"
        echo "::set-output name=has_changes::$(git diff --exit-code || echo 'true')"

    - name: Push changes to your fork
      if: steps.changes.outputs.has_changes == 'true'
      run: |
        git push origin master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Done
      if: steps.changes.outputs.has_changes != 'true'
      run: echo "No changes to push, workflow completed successfully."
