name: Fork Sync

on:
  schedule:
    - cron: '55 0 * * *'
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo (your fork)
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name "pavlojs"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global credential.helper 'store'
          git config --global url."https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com".insteadOf "https://github.com"

      - name: Add upstream repository
        run: |
          git remote add upstream https://github.com/bastienwirtz/homer.git
          git fetch upstream main

      - name: Merge upstream changes into master
        run: |
          git checkout master
          git merge upstream/main --allow-unrelated-histories -m "Sync fork with upstream"

      - name: Push changes to your fork
        run: |
          git add .
          git commit -m "Sync fork with upstream"
          git push origin master
